import JSZip from 'jszip'
import { getResource, type ResourceType } from '@/resources'
import type { ResourceNodeType } from '@/store/useGraphStore'

/**
 * Terraform generation (Phase 4). Each resource owns its HCL emitter
 * (`ResourceMeta.terraform`); this module resolves cross-resource references
 * from the graph topology, assembles the files, and zips them for download.
 * The goal is to pass `terraform validate` — not `terraform apply`. See ADR 0013.
 */

/** Terraform-safe local resource name (label / reference), e.g. `subnet_1`. */
function tfName(id: string): string {
  const n = id.replace(/[^a-zA-Z0-9_]/g, '_')
  return /^[a-zA-Z_]/.test(n) ? n : `r_${n}`
}

/** Value safe for AWS `name` attributes (alphanumeric + hyphen). */
function awsName(id: string): string {
  return id.replace(/[^a-zA-Z0-9-]/g, '-')
}

/** Emit order so the file reads network-outward. */
const ORDER: ResourceType[] = [
  'vpc', 'subnet', 'igw', 'nat', 'sg', 'alb', 'ec2', 'rds', 's3', 'lambda',
]

function ancestorOfType(
  node: ResourceNodeType,
  type: ResourceType,
  byId: Map<string, ResourceNodeType>,
): ResourceNodeType | undefined {
  let cur = node.parentId ? byId.get(node.parentId) : undefined
  while (cur) {
    if (cur.data.type === type) return cur
    cur = cur.parentId ? byId.get(cur.parentId) : undefined
  }
  return undefined
}

/** Builds the `main.tf` / `variables.tf` / `README.md` contents for a graph. */
export function generateTerraform(nodes: ResourceNodeType[]): Record<string, string> {
  const byId = new Map(nodes.map((n) => [n.id, n]))
  const vpcOf = (n: ResourceNodeType) => ancestorOfType(n, 'vpc', byId)

  const ordered = [...nodes].sort(
    (a, b) => ORDER.indexOf(a.data.type) - ORDER.indexOf(b.data.type),
  )

  const blocks = ordered
    .map((node) => {
      const vpc = vpcOf(node)
      const subnet = ancestorOfType(node, 'subnet', byId)
      const subnets = vpc
        ? nodes.filter((n) => n.data.type === 'subnet' && vpcOf(n)?.id === vpc.id)
        : []
      const securityGroups = vpc
        ? nodes.filter((n) => n.data.type === 'sg' && vpcOf(n)?.id === vpc.id)
        : []
      return getResource(node.data.type).terraform({
        name: tfName(node.id),
        awsName: awsName(node.id),
        config: node.data.config,
        refs: {
          vpc: vpc ? tfName(vpc.id) : undefined,
          subnet: subnet ? tfName(subnet.id) : undefined,
          subnets: subnets.map((s) => tfName(s.id)),
          securityGroups: securityGroups.map((s) => tfName(s.id)),
        },
      })
    })
    .filter((b) => b.trim() !== '')

  const hasType = (t: ResourceType) => nodes.some((n) => n.data.type === t)

  const mainTf = `# Generated by cidrunner — https://nextchans.github.io/cidrunner/
# Goal: pass \`terraform validate\`. Placeholder values (secrets, AMIs, IAM role)
# must be replaced before \`terraform apply\`.

terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

${blocks.join('\n\n')}
`

  const vars: string[] = [
    `variable "aws_region" {
  type    = string
  default = "ap-northeast-2"
}`,
  ]
  if (hasType('rds')) {
    vars.push(`variable "db_password" {
  type      = string
  sensitive = true
  default   = "ChangeMe123!" # placeholder — replace before use
}`)
  }
  if (hasType('lambda')) {
    vars.push(`variable "lambda_role_arn" {
  type    = string
  default = "arn:aws:iam::000000000000:role/lambda-exec" # placeholder
}`)
  }

  const readme = `# cidrunner Terraform export

Generated from your cidrunner canvas. This aims to pass \`terraform validate\`,
not \`terraform apply\` — placeholder values (DB password, Lambda IAM role,
AMI id, Lambda deployment package) must be filled in for a real deployment.

\`\`\`bash
terraform init
terraform validate
\`\`\`
`

  return {
    'main.tf': mainTf,
    'variables.tf': vars.join('\n\n') + '\n',
    'README.md': readme,
  }
}

/** Generates the Terraform files and triggers a browser zip download. */
export async function downloadTerraformZip(nodes: ResourceNodeType[]): Promise<void> {
  const files = generateTerraform(nodes)
  const zip = new JSZip()
  for (const [filename, content] of Object.entries(files)) {
    zip.file(filename, content)
  }
  const blob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = 'cidrunner-terraform.zip'
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}
